In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [6]:
series_obj = pd.Series(np.arange(8), index=["row " + str(i) for i in range(1,9)])
series_obj

row 1    0
row 2    1
row 3    2
row 4    3
row 5    4
row 6    5
row 7    6
row 8    7
dtype: int64

In [7]:
series_obj["row 7"]

6

In [10]:
series_obj[[0,7]]

row 1    0
row 8    7
dtype: int64

In [12]:
np.random.seed(25)
DF_obj = pd.DataFrame(
    np.random.rand(36).reshape((6,6)), 
    index=["row "+ str(i) for i in range(1,7)], 
    columns=["column "+ str(i) for i in range(1,7)]
)
DF_obj

<div>
<style>
    .dataframe thead tr:only-child th {
        text-align: right;
    }

    .dataframe thead th {
        text-align: left;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>column 1</th>
      <th>column 2</th>
      <th>column 3</th>
      <th>column 4</th>
      <th>column 5</th>
      <th>column 6</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>row 1</th>
      <td>0.870124</td>
      <td>0.582277</td>
      <td>0.278839</td>
      <td>0.185911</td>
      <td>0.411100</td>
      <td>0.117376</td>
    </tr>
    <tr>
      <th>row 2</th>
      <td>0.684969</td>
      <td>0.437611</td>
      <td>0.556229</td>
      <td>0.367080</td>
      <td>0.402366</td>
      <td>0.113041</td>
    </tr>
    <tr>
      <th>row 3</th>
      <td>0.447031</td>
      <td>0.585445</td>
      <td>0.161985</td>
      <td>0.520719</td>
      <td>0.326051</td>
      <td>0.699186</td>
    </tr>
    <tr>
      <th>row 4</th>
      <td>0.366395</td>
      <td>0.836375</td>
      <td>0.481343</td>
      <td>0.516502</td>
      <td>0.383048</td>
      <td>0.997541</td>
    </tr>
    <tr>
      <th>row 5</th>
      <td>0.514244</td>
      <td>0.559053</td>
      <td>0.034450</td>
      <td>0.719930</td>
      <td>0.421004</td>
      <td>0.436935</td>
    </tr>
    <tr>
      <th>row 6</th>
      <td>0.281701</td>
      <td>0.900274</td>
      <td>0.669612</td>
      <td>0.456069</td>
      <td>0.289804</td>
      <td>0.525819</td>
    </tr>
  </tbody>
</table>
</div>

In [15]:
DF_obj.loc[["row 2", "row 5"],["column 1"]]

<div>
<style>
    .dataframe thead tr:only-child th {
        text-align: right;
    }

    .dataframe thead th {
        text-align: left;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>column 1</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>row 2</th>
      <td>0.684969</td>
    </tr>
    <tr>
      <th>row 5</th>
      <td>0.514244</td>
    </tr>
  </tbody>
</table>
</div>

In [16]:
series_obj["row 3":"row 7"]

row 3    2
row 4    3
row 5    4
row 6    5
row 7    6
dtype: int64

In [17]:
DF_obj < .2

<div>
<style>
    .dataframe thead tr:only-child th {
        text-align: right;
    }

    .dataframe thead th {
        text-align: left;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>column 1</th>
      <th>column 2</th>
      <th>column 3</th>
      <th>column 4</th>
      <th>column 5</th>
      <th>column 6</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>row 1</th>
      <td>False</td>
      <td>False</td>
      <td>False</td>
      <td>True</td>
      <td>False</td>
      <td>True</td>
    </tr>
    <tr>
      <th>row 2</th>
      <td>False</td>
      <td>False</td>
      <td>False</td>
      <td>False</td>
      <td>False</td>
      <td>True</td>
    </tr>
    <tr>
      <th>row 3</th>
      <td>False</td>
      <td>False</td>
      <td>True</td>
      <td>False</td>
      <td>False</td>
      <td>False</td>
    </tr>
    <tr>
      <th>row 4</th>
      <td>False</td>
      <td>False</td>
      <td>False</td>
      <td>False</td>
      <td>False</td>
      <td>False</td>
    </tr>
    <tr>
      <th>row 5</th>
      <td>False</td>
      <td>False</td>
      <td>True</td>
      <td>False</td>
      <td>False</td>
      <td>False</td>
    </tr>
    <tr>
      <th>row 6</th>
      <td>False</td>
      <td>False</td>
      <td>False</td>
      <td>False</td>
      <td>False</td>
      <td>False</td>
    </tr>
  </tbody>
</table>
</div>

In [19]:
series_obj[series_obj > 6]

row 8    7
dtype: int64

In [23]:
DF_obj[DF_obj > 0.2]

<div>
<style>
    .dataframe thead tr:only-child th {
        text-align: right;
    }

    .dataframe thead th {
        text-align: left;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>column 1</th>
      <th>column 2</th>
      <th>column 3</th>
      <th>column 4</th>
      <th>column 5</th>
      <th>column 6</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>row 1</th>
      <td>0.870124</td>
      <td>0.582277</td>
      <td>0.278839</td>
      <td>NaN</td>
      <td>0.411100</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>row 2</th>
      <td>0.684969</td>
      <td>0.437611</td>
      <td>0.556229</td>
      <td>0.367080</td>
      <td>0.402366</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>row 3</th>
      <td>0.447031</td>
      <td>0.585445</td>
      <td>NaN</td>
      <td>0.520719</td>
      <td>0.326051</td>
      <td>0.699186</td>
    </tr>
    <tr>
      <th>row 4</th>
      <td>0.366395</td>
      <td>0.836375</td>
      <td>0.481343</td>
      <td>0.516502</td>
      <td>0.383048</td>
      <td>0.997541</td>
    </tr>
    <tr>
      <th>row 5</th>
      <td>0.514244</td>
      <td>0.559053</td>
      <td>NaN</td>
      <td>0.719930</td>
      <td>0.421004</td>
      <td>0.436935</td>
    </tr>
    <tr>
      <th>row 6</th>
      <td>0.281701</td>
      <td>0.900274</td>
      <td>0.669612</td>
      <td>0.456069</td>
      <td>0.289804</td>
      <td>0.525819</td>
    </tr>
  </tbody>
</table>
</div>

In [25]:
series_obj["row 1", "row 5", "row 8"] = 8

In [26]:
series_obj

row 1    8
row 2    1
row 3    2
row 4    3
row 5    8
row 6    5
row 7    6
row 8    8
dtype: int64

In [27]:
missing = np.nan

In [29]:
series_obj = pd.Series(["row " + str(i) for i in range(1, 9)])
series_obj[2, 6] = missing
series_obj

0    row 1
1    row 2
2      NaN
3    row 4
4    row 5
5    row 6
6      NaN
7    row 8
dtype: object

In [30]:
series_obj.isnull()

0    False
1    False
2     True
3    False
4    False
5    False
6     True
7    False
dtype: bool

In [31]:
DF_obj = pd.DataFrame(np.random.rand(36).reshape((6,6)))
DF_obj

<div>
<style>
    .dataframe thead tr:only-child th {
        text-align: right;
    }

    .dataframe thead th {
        text-align: left;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>0</th>
      <th>1</th>
      <th>2</th>
      <th>3</th>
      <th>4</th>
      <th>5</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>0.559242</td>
      <td>0.745284</td>
      <td>0.828346</td>
      <td>0.823694</td>
      <td>0.077140</td>
      <td>0.644862</td>
    </tr>
    <tr>
      <th>1</th>
      <td>0.309258</td>
      <td>0.524254</td>
      <td>0.958092</td>
      <td>0.883201</td>
      <td>0.295432</td>
      <td>0.512376</td>
    </tr>
    <tr>
      <th>2</th>
      <td>0.088702</td>
      <td>0.641717</td>
      <td>0.132421</td>
      <td>0.766486</td>
      <td>0.076742</td>
      <td>0.331044</td>
    </tr>
    <tr>
      <th>3</th>
      <td>0.679852</td>
      <td>0.509213</td>
      <td>0.655146</td>
      <td>0.602120</td>
      <td>0.719055</td>
      <td>0.415219</td>
    </tr>
    <tr>
      <th>4</th>
      <td>0.396542</td>
      <td>0.825139</td>
      <td>0.712552</td>
      <td>0.097937</td>
      <td>0.842154</td>
      <td>0.440821</td>
    </tr>
    <tr>
      <th>5</th>
      <td>0.373989</td>
      <td>0.913676</td>
      <td>0.547778</td>
      <td>0.251937</td>
      <td>0.027474</td>
      <td>0.206257</td>
    </tr>
  </tbody>
</table>
</div>

In [34]:
DF_obj.loc[3:5, 0] = missing
DF_obj.loc[1:4, 5] = missing
DF_obj

<div>
<style>
    .dataframe thead tr:only-child th {
        text-align: right;
    }

    .dataframe thead th {
        text-align: left;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>0</th>
      <th>1</th>
      <th>2</th>
      <th>3</th>
      <th>4</th>
      <th>5</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>0.559242</td>
      <td>0.745284</td>
      <td>0.828346</td>
      <td>0.823694</td>
      <td>0.077140</td>
      <td>0.644862</td>
    </tr>
    <tr>
      <th>1</th>
      <td>0.309258</td>
      <td>0.524254</td>
      <td>0.958092</td>
      <td>0.883201</td>
      <td>0.295432</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>2</th>
      <td>0.088702</td>
      <td>0.641717</td>
      <td>0.132421</td>
      <td>0.766486</td>
      <td>0.076742</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>3</th>
      <td>NaN</td>
      <td>0.509213</td>
      <td>0.655146</td>
      <td>0.602120</td>
      <td>0.719055</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>4</th>
      <td>NaN</td>
      <td>0.825139</td>
      <td>0.712552</td>
      <td>0.097937</td>
      <td>0.842154</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>5</th>
      <td>NaN</td>
      <td>0.913676</td>
      <td>0.547778</td>
      <td>0.251937</td>
      <td>0.027474</td>
      <td>0.206257</td>
    </tr>
  </tbody>
</table>
</div>

In [35]:
filled_DF = DF_obj.fillna(0)
filled_DF

<div>
<style>
    .dataframe thead tr:only-child th {
        text-align: right;
    }

    .dataframe thead th {
        text-align: left;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>0</th>
      <th>1</th>
      <th>2</th>
      <th>3</th>
      <th>4</th>
      <th>5</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>0.559242</td>
      <td>0.745284</td>
      <td>0.828346</td>
      <td>0.823694</td>
      <td>0.077140</td>
      <td>0.644862</td>
    </tr>
    <tr>
      <th>1</th>
      <td>0.309258</td>
      <td>0.524254</td>
      <td>0.958092</td>
      <td>0.883201</td>
      <td>0.295432</td>
      <td>0.000000</td>
    </tr>
    <tr>
      <th>2</th>
      <td>0.088702</td>
      <td>0.641717</td>
      <td>0.132421</td>
      <td>0.766486</td>
      <td>0.076742</td>
      <td>0.000000</td>
    </tr>
    <tr>
      <th>3</th>
      <td>0.000000</td>
      <td>0.509213</td>
      <td>0.655146</td>
      <td>0.602120</td>
      <td>0.719055</td>
      <td>0.000000</td>
    </tr>
    <tr>
      <th>4</th>
      <td>0.000000</td>
      <td>0.825139</td>
      <td>0.712552</td>
      <td>0.097937</td>
      <td>0.842154</td>
      <td>0.000000</td>
    </tr>
    <tr>
      <th>5</th>
      <td>0.000000</td>
      <td>0.913676</td>
      <td>0.547778</td>
      <td>0.251937</td>
      <td>0.027474</td>
      <td>0.206257</td>
    </tr>
  </tbody>
</table>
</div>

In [37]:
filled_DF = DF_obj.fillna({0: 0.1, 5: 1.25})
filled_DF

<div>
<style>
    .dataframe thead tr:only-child th {
        text-align: right;
    }

    .dataframe thead th {
        text-align: left;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>0</th>
      <th>1</th>
      <th>2</th>
      <th>3</th>
      <th>4</th>
      <th>5</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>0.559242</td>
      <td>0.745284</td>
      <td>0.828346</td>
      <td>0.823694</td>
      <td>0.077140</td>
      <td>0.644862</td>
    </tr>
    <tr>
      <th>1</th>
      <td>0.309258</td>
      <td>0.524254</td>
      <td>0.958092</td>
      <td>0.883201</td>
      <td>0.295432</td>
      <td>1.250000</td>
    </tr>
    <tr>
      <th>2</th>
      <td>0.088702</td>
      <td>0.641717</td>
      <td>0.132421</td>
      <td>0.766486</td>
      <td>0.076742</td>
      <td>1.250000</td>
    </tr>
    <tr>
      <th>3</th>
      <td>0.100000</td>
      <td>0.509213</td>
      <td>0.655146</td>
      <td>0.602120</td>
      <td>0.719055</td>
      <td>1.250000</td>
    </tr>
    <tr>
      <th>4</th>
      <td>0.100000</td>
      <td>0.825139</td>
      <td>0.712552</td>
      <td>0.097937</td>
      <td>0.842154</td>
      <td>1.250000</td>
    </tr>
    <tr>
      <th>5</th>
      <td>0.100000</td>
      <td>0.913676</td>
      <td>0.547778</td>
      <td>0.251937</td>
      <td>0.027474</td>
      <td>0.206257</td>
    </tr>
  </tbody>
</table>
</div>

In [38]:
fill_DF = DF_obj.fillna(method="ffill")
fill_DF

<div>
<style>
    .dataframe thead tr:only-child th {
        text-align: right;
    }

    .dataframe thead th {
        text-align: left;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>0</th>
      <th>1</th>
      <th>2</th>
      <th>3</th>
      <th>4</th>
      <th>5</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>0.559242</td>
      <td>0.745284</td>
      <td>0.828346</td>
      <td>0.823694</td>
      <td>0.077140</td>
      <td>0.644862</td>
    </tr>
    <tr>
      <th>1</th>
      <td>0.309258</td>
      <td>0.524254</td>
      <td>0.958092</td>
      <td>0.883201</td>
      <td>0.295432</td>
      <td>0.644862</td>
    </tr>
    <tr>
      <th>2</th>
      <td>0.088702</td>
      <td>0.641717</td>
      <td>0.132421</td>
      <td>0.766486</td>
      <td>0.076742</td>
      <td>0.644862</td>
    </tr>
    <tr>
      <th>3</th>
      <td>0.088702</td>
      <td>0.509213</td>
      <td>0.655146</td>
      <td>0.602120</td>
      <td>0.719055</td>
      <td>0.644862</td>
    </tr>
    <tr>
      <th>4</th>
      <td>0.088702</td>
      <td>0.825139</td>
      <td>0.712552</td>
      <td>0.097937</td>
      <td>0.842154</td>
      <td>0.644862</td>
    </tr>
    <tr>
      <th>5</th>
      <td>0.088702</td>
      <td>0.913676</td>
      <td>0.547778</td>
      <td>0.251937</td>
      <td>0.027474</td>
      <td>0.206257</td>
    </tr>
  </tbody>
</table>
</div>

In [ ]:
my_df = pd.DataFrame(np.random.rand(36).reshape((6,6))) 
my_df * 10

<div>
<style>
    .dataframe thead tr:only-child th {
        text-align: right;
    }

    .dataframe thead th {
        text-align: left;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>0</th>
      <th>1</th>
      <th>2</th>
      <th>3</th>
      <th>4</th>
      <th>5</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>0.672758</td>
      <td>0.976990</td>
      <td>0.440174</td>
      <td>0.077918</td>
      <td>0.386085</td>
      <td>0.325661</td>
    </tr>
    <tr>
      <th>1</th>
      <td>0.758764</td>
      <td>0.283726</td>
      <td>0.280196</td>
      <td>0.558928</td>
      <td>0.131789</td>
      <td>0.180604</td>
    </tr>
    <tr>
      <th>2</th>
      <td>0.437088</td>
      <td>0.528345</td>
      <td>0.266845</td>
      <td>0.117473</td>
      <td>0.405581</td>
      <td>0.449468</td>
    </tr>
    <tr>
      <th>3</th>
      <td>0.660972</td>
      <td>0.004293</td>
      <td>0.976243</td>
      <td>0.227928</td>
      <td>0.004887</td>
      <td>0.060370</td>
    </tr>
    <tr>
      <th>4</th>
      <td>0.857940</td>
      <td>0.702012</td>
      <td>0.911328</td>
      <td>0.937312</td>
      <td>0.027804</td>
      <td>0.295813</td>
    </tr>
    <tr>
      <th>5</th>
      <td>0.441484</td>
      <td>0.399950</td>
      <td>0.703941</td>
      <td>0.601116</td>
      <td>0.423105</td>
      <td>0.491360</td>
    </tr>
  </tbody>
</table>
</div>

In [6]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import bokeh.plotting as bk

from bokeh.models import (
    ColumnDataSource,
    HoverTool,
    LinearColorMapper,
    BasicTicker,
    PrintfTickFormatter,
    ColorBar,
)

from bokeh.sampledata.unemployment1948 import data
data

<div>
<style>
    .dataframe thead tr:only-child th {
        text-align: right;
    }

    .dataframe thead th {
        text-align: left;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>Year</th>
      <th>Jan</th>
      <th>Feb</th>
      <th>Mar</th>
      <th>Apr</th>
      <th>May</th>
      <th>Jun</th>
      <th>Jul</th>
      <th>Aug</th>
      <th>Sep</th>
      <th>Oct</th>
      <th>Nov</th>
      <th>Dec</th>
      <th>Annual</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>1948</td>
      <td>4.0</td>
      <td>4.7</td>
      <td>4.5</td>
      <td>4.0</td>
      <td>3.4</td>
      <td>3.9</td>
      <td>3.9</td>
      <td>3.6</td>
      <td>3.4</td>
      <td>2.9</td>
      <td>3.3</td>
      <td>3.6</td>
      <td>3.8</td>
    </tr>
    <tr>
      <th>1</th>
      <td>1949</td>
      <td>5.0</td>
      <td>5.8</td>
      <td>5.6</td>
      <td>5.4</td>
      <td>5.7</td>
      <td>6.4</td>
      <td>7.0</td>
      <td>6.3</td>
      <td>5.9</td>
      <td>6.1</td>
      <td>5.7</td>
      <td>6.0</td>
      <td>5.9</td>
    </tr>
    <tr>
      <th>2</th>
      <td>1950</td>
      <td>7.6</td>
      <td>7.9</td>
      <td>7.1</td>
      <td>6.0</td>
      <td>5.3</td>
      <td>5.6</td>
      <td>5.3</td>
      <td>4.1</td>
      <td>4.0</td>
      <td>3.3</td>
      <td>3.8</td>
      <td>3.9</td>
      <td>5.3</td>
    </tr>
    <tr>
      <th>3</th>
      <td>1951</td>
      <td>4.4</td>
      <td>4.2</td>
      <td>3.8</td>
      <td>3.2</td>
      <td>2.9</td>
      <td>3.4</td>
      <td>3.3</td>
      <td>2.9</td>
      <td>3.0</td>
      <td>2.8</td>
      <td>3.2</td>
      <td>2.9</td>
      <td>3.3</td>
    </tr>
    <tr>
      <th>4</th>
      <td>1952</td>
      <td>3.7</td>
      <td>3.8</td>
      <td>3.3</td>
      <td>3.0</td>
      <td>2.9</td>
      <td>3.2</td>
      <td>3.3</td>
      <td>3.1</td>
      <td>2.7</td>
      <td>2.4</td>
      <td>2.5</td>
      <td>2.5</td>
      <td>3.0</td>
    </tr>
    <tr>
      <th>5</th>
      <td>1953</td>
      <td>3.4</td>
      <td>3.2</td>
      <td>2.9</td>
      <td>2.8</td>
      <td>2.5</td>
      <td>2.7</td>
      <td>2.7</td>
      <td>2.4</td>
      <td>2.6</td>
      <td>2.5</td>
      <td>3.2</td>
      <td>4.2</td>
      <td>2.9</td>
    </tr>
    <tr>
      <th>6</th>
      <td>1954</td>
      <td>5.7</td>
      <td>6.3</td>
      <td>6.4</td>
      <td>6.1</td>
      <td>5.7</td>
      <td>5.7</td>
      <td>5.7</td>
      <td>5.4</td>
      <td>5.3</td>
      <td>4.6</td>
      <td>4.9</td>
      <td>4.8</td>
      <td>5.5</td>
    </tr>
    <tr>
      <th>7</th>
      <td>1955</td>
      <td>5.8</td>
      <td>5.7</td>
      <td>5.2</td>
      <td>4.9</td>
      <td>4.2</td>
      <td>4.4</td>
      <td>4.0</td>
      <td>3.8</td>
      <td>3.5</td>
      <td>3.4</td>
      <td>3.8</td>
      <td>3.9</td>
      <td>4.4</td>
    </tr>
    <tr>
      <th>8</th>
      <td>1956</td>
      <td>4.7</td>
      <td>4.8</td>
      <td>4.7</td>
      <td>4.1</td>
      <td>4.2</td>
      <td>4.7</td>
      <td>4.4</td>
      <td>3.7</td>
      <td>3.4</td>
      <td>3.1</td>
      <td>3.9</td>
      <td>4.0</td>
      <td>4.1</td>
    </tr>
    <tr>
      <th>9</th>
      <td>1957</td>
      <td>4.9</td>
      <td>4.7</td>
      <td>4.3</td>
      <td>4.0</td>
      <td>3.9</td>
      <td>4.6</td>
      <td>4.1</td>
      <td>3.7</td>
      <td>3.7</td>
      <td>3.6</td>
      <td>4.6</td>
      <td>5.0</td>
      <td>4.3</td>
    </tr>
    <tr>
      <th>10</th>
      <td>1958</td>
      <td>6.8</td>
      <td>7.7</td>
      <td>7.7</td>
      <td>7.5</td>
      <td>7.1</td>
      <td>7.6</td>
      <td>7.4</td>
      <td>6.7</td>
      <td>6.0</td>
      <td>5.5</td>
      <td>5.6</td>
      <td>6.0</td>
      <td>6.8</td>
    </tr>
    <tr>
      <th>11</th>
      <td>1959</td>
      <td>7.0</td>
      <td>7.0</td>
      <td>6.4</td>
      <td>5.2</td>
      <td>4.9</td>
      <td>5.4</td>
      <td>5.2</td>
      <td>4.8</td>
      <td>4.7</td>
      <td>4.7</td>
      <td>5.3</td>
      <td>5.1</td>
      <td>5.5</td>
    </tr>
    <tr>
      <th>12</th>
      <td>1960</td>
      <td>6.1</td>
      <td>5.7</td>
      <td>6.1</td>
      <td>5.2</td>
      <td>4.8</td>
      <td>5.8</td>
      <td>5.5</td>
      <td>5.2</td>
      <td>4.7</td>
      <td>5.0</td>
      <td>5.6</td>
      <td>6.4</td>
      <td>5.5</td>
    </tr>
    <tr>
      <th>13</th>
      <td>1961</td>
      <td>7.7</td>
      <td>8.1</td>
      <td>7.7</td>
      <td>7.0</td>
      <td>6.6</td>
      <td>7.3</td>
      <td>6.9</td>
      <td>6.2</td>
      <td>5.8</td>
      <td>5.5</td>
      <td>5.6</td>
      <td>5.8</td>
      <td>6.7</td>
    </tr>
    <tr>
      <th>14</th>
      <td>1962</td>
      <td>6.7</td>
      <td>6.5</td>
      <td>6.2</td>
      <td>5.5</td>
      <td>5.1</td>
      <td>5.9</td>
      <td>5.3</td>
      <td>5.3</td>
      <td>4.9</td>
      <td>4.5</td>
      <td>5.3</td>
      <td>5.3</td>
      <td>5.5</td>
    </tr>
    <tr>
      <th>15</th>
      <td>1963</td>
      <td>6.6</td>
      <td>6.9</td>
      <td>6.3</td>
      <td>5.6</td>
      <td>5.5</td>
      <td>6.2</td>
      <td>5.6</td>
      <td>5.2</td>
      <td>4.8</td>
      <td>4.7</td>
      <td>5.3</td>
      <td>5.3</td>
      <td>5.7</td>
    </tr>
    <tr>
      <th>16</th>
      <td>1964</td>
      <td>6.4</td>
      <td>6.2</td>
      <td>5.9</td>
      <td>5.3</td>
      <td>4.8</td>
      <td>5.9</td>
      <td>4.9</td>
      <td>4.8</td>
      <td>4.5</td>
      <td>4.4</td>
      <td>4.5</td>
      <td>4.7</td>
      <td>5.2</td>
    </tr>
    <tr>
      <th>17</th>
      <td>1965</td>
      <td>5.5</td>
      <td>5.7</td>
      <td>5.1</td>
      <td>4.7</td>
      <td>4.3</td>
      <td>5.3</td>
      <td>4.5</td>
      <td>4.2</td>
      <td>3.8</td>
      <td>3.6</td>
      <td>3.9</td>
      <td>3.7</td>
      <td>4.5</td>
    </tr>
    <tr>
      <th>18</th>
      <td>1966</td>
      <td>4.4</td>
      <td>4.2</td>
      <td>4.0</td>
      <td>3.6</td>
      <td>3.7</td>
      <td>4.6</td>
      <td>3.9</td>
      <td>3.6</td>
      <td>3.3</td>
      <td>3.2</td>
      <td>3.4</td>
      <td>3.5</td>
      <td>3.8</td>
    </tr>
    <tr>
      <th>19</th>
      <td>1967</td>
      <td>4.2</td>
      <td>4.2</td>
      <td>3.9</td>
      <td>3.5</td>
      <td>3.2</td>
      <td>4.6</td>
      <td>4.1</td>
      <td>3.7</td>
      <td>3.7</td>
      <td>3.8</td>
      <td>3.7</td>
      <td>3.5</td>
      <td>3.8</td>
    </tr>
    <tr>
      <th>20</th>
      <td>1968</td>
      <td>4.0</td>
      <td>4.2</td>
      <td>3.8</td>
      <td>3.2</td>
      <td>2.9</td>
      <td>4.5</td>
      <td>4.0</td>
      <td>3.5</td>
      <td>3.3</td>
      <td>3.2</td>
      <td>3.3</td>
      <td>3.1</td>
      <td>3.6</td>
    </tr>
    <tr>
      <th>21</th>
      <td>1969</td>
      <td>3.7</td>
      <td>3.7</td>
      <td>3.5</td>
      <td>3.2</td>
      <td>2.9</td>
      <td>4.1</td>
      <td>3.8</td>
      <td>3.5</td>
      <td>3.7</td>
      <td>3.5</td>
      <td>3.3</td>
      <td>3.2</td>
      <td>3.5</td>
    </tr>
    <tr>
      <th>22</th>
      <td>1970</td>
      <td>4.2</td>
      <td>4.7</td>
      <td>4.6</td>
      <td>4.3</td>
      <td>4.1</td>
      <td>5.6</td>
      <td>5.3</td>
      <td>5.0</td>
      <td>5.2</td>
      <td>5.1</td>
      <td>5.5</td>
      <td>5.6</td>
      <td>4.9</td>
    </tr>
    <tr>
      <th>23</th>
      <td>1971</td>
      <td>6.6</td>
      <td>6.6</td>
      <td>6.3</td>
      <td>5.7</td>
      <td>5.3</td>
      <td>6.5</td>
      <td>6.2</td>
      <td>5.9</td>
      <td>5.8</td>
      <td>5.4</td>
      <td>5.7</td>
      <td>5.5</td>
      <td>5.9</td>
    </tr>
    <tr>
      <th>24</th>
      <td>1972</td>
      <td>6.5</td>
      <td>6.4</td>
      <td>6.1</td>
      <td>5.5</td>
      <td>5.1</td>
      <td>6.2</td>
      <td>5.9</td>
      <td>5.5</td>
      <td>5.4</td>
      <td>5.1</td>
      <td>4.9</td>
      <td>4.8</td>
      <td>5.6</td>
    </tr>
    <tr>
      <th>25</th>
      <td>1973</td>
      <td>5.5</td>
      <td>5.6</td>
      <td>5.2</td>
      <td>4.8</td>
      <td>4.4</td>
      <td>5.4</td>
      <td>5.0</td>
      <td>4.7</td>
      <td>4.7</td>
      <td>4.2</td>
      <td>4.6</td>
      <td>4.6</td>
      <td>4.9</td>
    </tr>
    <tr>
      <th>26</th>
      <td>1974</td>
      <td>5.7</td>
      <td>5.8</td>
      <td>5.3</td>
      <td>4.8</td>
      <td>4.6</td>
      <td>5.8</td>
      <td>5.7</td>
      <td>5.3</td>
      <td>5.7</td>
      <td>5.5</td>
      <td>6.2</td>
      <td>6.7</td>
      <td>5.6</td>
    </tr>
    <tr>
      <th>27</th>
      <td>1975</td>
      <td>9.0</td>
      <td>9.1</td>
      <td>9.1</td>
      <td>8.6</td>
      <td>8.3</td>
      <td>9.1</td>
      <td>8.7</td>
      <td>8.2</td>
      <td>8.1</td>
      <td>7.8</td>
      <td>7.8</td>
      <td>7.8</td>
      <td>8.5</td>
    </tr>
    <tr>
      <th>28</th>
      <td>1976</td>
      <td>8.8</td>
      <td>8.7</td>
      <td>8.1</td>
      <td>7.4</td>
      <td>6.8</td>
      <td>8.0</td>
      <td>7.8</td>
      <td>7.6</td>
      <td>7.4</td>
      <td>7.2</td>
      <td>7.4</td>
      <td>7.4</td>
      <td>7.7</td>
    </tr>
    <tr>
      <th>29</th>
      <td>1977</td>
      <td>8.3</td>
      <td>8.5</td>
      <td>7.9</td>
      <td>6.9</td>
      <td>6.4</td>
      <td>7.5</td>
      <td>7.0</td>
      <td>6.8</td>
      <td>6.6</td>
      <td>6.4</td>
      <td>6.5</td>
      <td>6.0</td>
      <td>7.1</td>
    </tr>
    <tr>
      <th>...</th>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
    </tr>
    <tr>
      <th>39</th>
      <td>1987</td>
      <td>7.3</td>
      <td>7.2</td>
      <td>6.9</td>
      <td>6.2</td>
      <td>6.1</td>
      <td>6.3</td>
      <td>6.1</td>
      <td>5.8</td>
      <td>5.7</td>
      <td>5.7</td>
      <td>5.6</td>
      <td>5.4</td>
      <td>6.2</td>
    </tr>
    <tr>
      <th>40</th>
      <td>1988</td>
      <td>6.3</td>
      <td>6.2</td>
      <td>5.9</td>
      <td>5.3</td>
      <td>5.4</td>
      <td>5.5</td>
      <td>5.5</td>
      <td>5.4</td>
      <td>5.2</td>
      <td>5.0</td>
      <td>5.2</td>
      <td>5.0</td>
      <td>5.5</td>
    </tr>
    <tr>
      <th>41</th>
      <td>1989</td>
      <td>6.0</td>
      <td>5.6</td>
      <td>5.2</td>
      <td>5.1</td>
      <td>5.0</td>
      <td>5.5</td>
      <td>5.3</td>
      <td>5.1</td>
      <td>5.1</td>
      <td>5.0</td>
      <td>5.2</td>
      <td>5.1</td>
      <td>5.3</td>
    </tr>
    <tr>
      <th>42</th>
      <td>1990</td>
      <td>6.0</td>
      <td>5.9</td>
      <td>5.5</td>
      <td>5.3</td>
      <td>5.2</td>
      <td>5.4</td>
      <td>5.6</td>
      <td>5.5</td>
      <td>5.6</td>
      <td>5.5</td>
      <td>5.9</td>
      <td>6.0</td>
      <td>5.6</td>
    </tr>
    <tr>
      <th>43</th>
      <td>1991</td>
      <td>7.1</td>
      <td>7.3</td>
      <td>7.2</td>
      <td>6.5</td>
      <td>6.7</td>
      <td>7.0</td>
      <td>6.8</td>
      <td>6.6</td>
      <td>6.5</td>
      <td>6.5</td>
      <td>6.7</td>
      <td>6.9</td>
      <td>6.8</td>
    </tr>
    <tr>
      <th>44</th>
      <td>1992</td>
      <td>8.1</td>
      <td>8.2</td>
      <td>7.8</td>
      <td>7.2</td>
      <td>7.3</td>
      <td>8.0</td>
      <td>7.7</td>
      <td>7.4</td>
      <td>7.3</td>
      <td>6.9</td>
      <td>7.1</td>
      <td>7.1</td>
      <td>7.5</td>
    </tr>
    <tr>
      <th>45</th>
      <td>1993</td>
      <td>8.0</td>
      <td>7.8</td>
      <td>7.4</td>
      <td>6.9</td>
      <td>6.8</td>
      <td>7.2</td>
      <td>7.0</td>
      <td>6.6</td>
      <td>6.4</td>
      <td>6.4</td>
      <td>6.2</td>
      <td>6.1</td>
      <td>6.9</td>
    </tr>
    <tr>
      <th>46</th>
      <td>1994</td>
      <td>7.3</td>
      <td>7.1</td>
      <td>6.8</td>
      <td>6.2</td>
      <td>5.9</td>
      <td>6.2</td>
      <td>6.2</td>
      <td>5.9</td>
      <td>5.6</td>
      <td>5.4</td>
      <td>5.3</td>
      <td>5.1</td>
      <td>6.1</td>
    </tr>
    <tr>
      <th>47</th>
      <td>1995</td>
      <td>6.2</td>
      <td>5.9</td>
      <td>5.7</td>
      <td>5.6</td>
      <td>5.5</td>
      <td>5.8</td>
      <td>5.9</td>
      <td>5.6</td>
      <td>5.4</td>
      <td>5.2</td>
      <td>5.3</td>
      <td>5.2</td>
      <td>5.6</td>
    </tr>
    <tr>
      <th>48</th>
      <td>1996</td>
      <td>6.3</td>
      <td>6.0</td>
      <td>5.8</td>
      <td>5.4</td>
      <td>5.4</td>
      <td>5.5</td>
      <td>5.6</td>
      <td>5.1</td>
      <td>5.0</td>
      <td>4.9</td>
      <td>5.0</td>
      <td>5.0</td>
      <td>5.4</td>
    </tr>
    <tr>
      <th>49</th>
      <td>1997</td>
      <td>5.9</td>
      <td>5.7</td>
      <td>5.5</td>
      <td>4.8</td>
      <td>4.7</td>
      <td>5.2</td>
      <td>5.0</td>
      <td>4.8</td>
      <td>4.7</td>
      <td>4.4</td>
      <td>4.3</td>
      <td>4.4</td>
      <td>4.9</td>
    </tr>
    <tr>
      <th>50</th>
      <td>1998</td>
      <td>5.2</td>
      <td>5.0</td>
      <td>5.0</td>
      <td>4.1</td>
      <td>4.2</td>
      <td>4.7</td>
      <td>4.7</td>
      <td>4.5</td>
      <td>4.4</td>
      <td>4.2</td>
      <td>4.1</td>
      <td>4.0</td>
      <td>4.5</td>
    </tr>
    <tr>
      <th>51</th>
      <td>1999</td>
      <td>4.8</td>
      <td>4.7</td>
      <td>4.4</td>
      <td>4.1</td>
      <td>4.0</td>
      <td>4.5</td>
      <td>4.5</td>
      <td>4.2</td>
      <td>4.1</td>
      <td>3.8</td>
      <td>3.8</td>
      <td>3.7</td>
      <td>4.2</td>
    </tr>
    <tr>
      <th>52</th>
      <td>2000</td>
      <td>4.5</td>
      <td>4.4</td>
      <td>4.3</td>
      <td>3.7</td>
      <td>3.8</td>
      <td>4.1</td>
      <td>4.2</td>
      <td>4.1</td>
      <td>3.8</td>
      <td>3.6</td>
      <td>3.7</td>
      <td>3.7</td>
      <td>4.0</td>
    </tr>
    <tr>
      <th>53</th>
      <td>2001</td>
      <td>4.7</td>
      <td>4.6</td>
      <td>4.5</td>
      <td>4.2</td>
      <td>4.1</td>
      <td>4.7</td>
      <td>4.7</td>
      <td>4.9</td>
      <td>4.7</td>
      <td>5.0</td>
      <td>5.3</td>
      <td>5.4</td>
      <td>4.7</td>
    </tr>
    <tr>
      <th>54</th>
      <td>2002</td>
      <td>6.3</td>
      <td>6.1</td>
      <td>6.1</td>
      <td>5.7</td>
      <td>5.5</td>
      <td>6.0</td>
      <td>5.9</td>
      <td>5.7</td>
      <td>5.4</td>
      <td>5.3</td>
      <td>5.6</td>
      <td>5.7</td>
      <td>5.8</td>
    </tr>
    <tr>
      <th>55</th>
      <td>2003</td>
      <td>6.5</td>
      <td>6.4</td>
      <td>6.2</td>
      <td>5.8</td>
      <td>5.8</td>
      <td>6.5</td>
      <td>6.3</td>
      <td>6.0</td>
      <td>5.8</td>
      <td>5.6</td>
      <td>5.6</td>
      <td>5.4</td>
      <td>6.0</td>
    </tr>
    <tr>
      <th>56</th>
      <td>2004</td>
      <td>6.3</td>
      <td>6.0</td>
      <td>6.0</td>
      <td>5.4</td>
      <td>5.3</td>
      <td>5.8</td>
      <td>5.7</td>
      <td>5.4</td>
      <td>5.1</td>
      <td>5.1</td>
      <td>5.2</td>
      <td>5.1</td>
      <td>5.5</td>
    </tr>
    <tr>
      <th>57</th>
      <td>2005</td>
      <td>5.7</td>
      <td>5.8</td>
      <td>5.4</td>
      <td>4.9</td>
      <td>4.9</td>
      <td>5.2</td>
      <td>5.2</td>
      <td>4.9</td>
      <td>4.8</td>
      <td>4.6</td>
      <td>4.8</td>
      <td>4.6</td>
      <td>5.1</td>
    </tr>
    <tr>
      <th>58</th>
      <td>2006</td>
      <td>5.1</td>
      <td>5.1</td>
      <td>4.8</td>
      <td>4.5</td>
      <td>4.4</td>
      <td>4.8</td>
      <td>5.0</td>
      <td>4.6</td>
      <td>4.4</td>
      <td>4.1</td>
      <td>4.3</td>
      <td>4.3</td>
      <td>4.6</td>
    </tr>
    <tr>
      <th>59</th>
      <td>2007</td>
      <td>5.0</td>
      <td>4.9</td>
      <td>4.5</td>
      <td>4.3</td>
      <td>4.3</td>
      <td>4.7</td>
      <td>4.9</td>
      <td>4.6</td>
      <td>4.5</td>
      <td>4.4</td>
      <td>4.5</td>
      <td>4.8</td>
      <td>4.6</td>
    </tr>
    <tr>
      <th>60</th>
      <td>2008</td>
      <td>5.4</td>
      <td>5.2</td>
      <td>5.2</td>
      <td>4.8</td>
      <td>5.2</td>
      <td>5.7</td>
      <td>6.0</td>
      <td>6.1</td>
      <td>6.0</td>
      <td>6.1</td>
      <td>6.5</td>
      <td>7.1</td>
      <td>5.8</td>
    </tr>
    <tr>
      <th>61</th>
      <td>2009</td>
      <td>8.5</td>
      <td>8.9</td>
      <td>9.0</td>
      <td>8.6</td>
      <td>9.1</td>
      <td>9.7</td>
      <td>9.7</td>
      <td>9.6</td>
      <td>9.5</td>
      <td>9.5</td>
      <td>9.4</td>
      <td>9.7</td>
      <td>9.3</td>
    </tr>
    <tr>
      <th>62</th>
      <td>2010</td>
      <td>10.6</td>
      <td>10.4</td>
      <td>10.2</td>
      <td>9.5</td>
      <td>9.3</td>
      <td>9.6</td>
      <td>9.7</td>
      <td>9.5</td>
      <td>9.2</td>
      <td>9.0</td>
      <td>9.3</td>
      <td>9.1</td>
      <td>9.6</td>
    </tr>
    <tr>
      <th>63</th>
      <td>2011</td>
      <td>9.8</td>
      <td>9.5</td>
      <td>9.2</td>
      <td>8.7</td>
      <td>8.7</td>
      <td>9.3</td>
      <td>9.3</td>
      <td>9.1</td>
      <td>8.8</td>
      <td>8.5</td>
      <td>8.2</td>
      <td>8.3</td>
      <td>8.9</td>
    </tr>
    <tr>
      <th>64</th>
      <td>2012</td>
      <td>8.8</td>
      <td>8.7</td>
      <td>8.4</td>
      <td>7.7</td>
      <td>7.9</td>
      <td>8.4</td>
      <td>8.6</td>
      <td>8.2</td>
      <td>7.6</td>
      <td>7.5</td>
      <td>7.4</td>
      <td>7.6</td>
      <td>8.1</td>
    </tr>
    <tr>
      <th>65</th>
      <td>2013</td>
      <td>8.5</td>
      <td>8.1</td>
      <td>7.6</td>
      <td>7.1</td>
      <td>7.3</td>
      <td>7.8</td>
      <td>7.7</td>
      <td>7.3</td>
      <td>7.0</td>
      <td>7.0</td>
      <td>6.6</td>
      <td>6.5</td>
      <td>7.4</td>
    </tr>
    <tr>
      <th>66</th>
      <td>2014</td>
      <td>7.0</td>
      <td>7.0</td>
      <td>6.8</td>
      <td>5.9</td>
      <td>6.1</td>
      <td>6.3</td>
      <td>6.5</td>
      <td>6.3</td>
      <td>5.7</td>
      <td>5.5</td>
      <td>5.5</td>
      <td>5.4</td>
      <td>6.2</td>
    </tr>
    <tr>
      <th>67</th>
      <td>2015</td>
      <td>6.1</td>
      <td>5.8</td>
      <td>5.6</td>
      <td>5.1</td>
      <td>5.3</td>
      <td>5.5</td>
      <td>5.6</td>
      <td>5.2</td>
      <td>4.9</td>
      <td>4.8</td>
      <td>4.8</td>
      <td>4.8</td>
      <td>5.3</td>
    </tr>
    <tr>
      <th>68</th>
      <td>2016</td>
      <td>5.3</td>
      <td>5.2</td>
      <td>5.1</td>
      <td>4.7</td>
      <td>4.5</td>
      <td>5.1</td>
      <td>5.1</td>
      <td>5.0</td>
      <td>4.8</td>
      <td>4.7</td>
      <td>4.4</td>
      <td>4.5</td>
      <td>4.9</td>
    </tr>
  </tbody>
</table>
<p>69 rows × 14 columns</p>
</div>

In [7]:
data['Year'] = data['Year'].astype(str)
data = data.set_index('Year')
data.drop('Annual', axis=1, inplace=True)
data.columns.name = 'Month'
data

<div>
<style>
    .dataframe thead tr:only-child th {
        text-align: right;
    }

    .dataframe thead th {
        text-align: left;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th>Month</th>
      <th>Jan</th>
      <th>Feb</th>
      <th>Mar</th>
      <th>Apr</th>
      <th>May</th>
      <th>Jun</th>
      <th>Jul</th>
      <th>Aug</th>
      <th>Sep</th>
      <th>Oct</th>
      <th>Nov</th>
      <th>Dec</th>
    </tr>
    <tr>
      <th>Year</th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>1948</th>
      <td>4.0</td>
      <td>4.7</td>
      <td>4.5</td>
      <td>4.0</td>
      <td>3.4</td>
      <td>3.9</td>
      <td>3.9</td>
      <td>3.6</td>
      <td>3.4</td>
      <td>2.9</td>
      <td>3.3</td>
      <td>3.6</td>
    </tr>
    <tr>
      <th>1949</th>
      <td>5.0</td>
      <td>5.8</td>
      <td>5.6</td>
      <td>5.4</td>
      <td>5.7</td>
      <td>6.4</td>
      <td>7.0</td>
      <td>6.3</td>
      <td>5.9</td>
      <td>6.1</td>
      <td>5.7</td>
      <td>6.0</td>
    </tr>
    <tr>
      <th>1950</th>
      <td>7.6</td>
      <td>7.9</td>
      <td>7.1</td>
      <td>6.0</td>
      <td>5.3</td>
      <td>5.6</td>
      <td>5.3</td>
      <td>4.1</td>
      <td>4.0</td>
      <td>3.3</td>
      <td>3.8</td>
      <td>3.9</td>
    </tr>
    <tr>
      <th>1951</th>
      <td>4.4</td>
      <td>4.2</td>
      <td>3.8</td>
      <td>3.2</td>
      <td>2.9</td>
      <td>3.4</td>
      <td>3.3</td>
      <td>2.9</td>
      <td>3.0</td>
      <td>2.8</td>
      <td>3.2</td>
      <td>2.9</td>
    </tr>
    <tr>
      <th>1952</th>
      <td>3.7</td>
      <td>3.8</td>
      <td>3.3</td>
      <td>3.0</td>
      <td>2.9</td>
      <td>3.2</td>
      <td>3.3</td>
      <td>3.1</td>
      <td>2.7</td>
      <td>2.4</td>
      <td>2.5</td>
      <td>2.5</td>
    </tr>
    <tr>
      <th>1953</th>
      <td>3.4</td>
      <td>3.2</td>
      <td>2.9</td>
      <td>2.8</td>
      <td>2.5</td>
      <td>2.7</td>
      <td>2.7</td>
      <td>2.4</td>
      <td>2.6</td>
      <td>2.5</td>
      <td>3.2</td>
      <td>4.2</td>
    </tr>
    <tr>
      <th>1954</th>
      <td>5.7</td>
      <td>6.3</td>
      <td>6.4</td>
      <td>6.1</td>
      <td>5.7</td>
      <td>5.7</td>
      <td>5.7</td>
      <td>5.4</td>
      <td>5.3</td>
      <td>4.6</td>
      <td>4.9</td>
      <td>4.8</td>
    </tr>
    <tr>
      <th>1955</th>
      <td>5.8</td>
      <td>5.7</td>
      <td>5.2</td>
      <td>4.9</td>
      <td>4.2</td>
      <td>4.4</td>
      <td>4.0</td>
      <td>3.8</td>
      <td>3.5</td>
      <td>3.4</td>
      <td>3.8</td>
      <td>3.9</td>
    </tr>
    <tr>
      <th>1956</th>
      <td>4.7</td>
      <td>4.8</td>
      <td>4.7</td>
      <td>4.1</td>
      <td>4.2</td>
      <td>4.7</td>
      <td>4.4</td>
      <td>3.7</td>
      <td>3.4</td>
      <td>3.1</td>
      <td>3.9</td>
      <td>4.0</td>
    </tr>
    <tr>
      <th>1957</th>
      <td>4.9</td>
      <td>4.7</td>
      <td>4.3</td>
      <td>4.0</td>
      <td>3.9</td>
      <td>4.6</td>
      <td>4.1</td>
      <td>3.7</td>
      <td>3.7</td>
      <td>3.6</td>
      <td>4.6</td>
      <td>5.0</td>
    </tr>
    <tr>
      <th>1958</th>
      <td>6.8</td>
      <td>7.7</td>
      <td>7.7</td>
      <td>7.5</td>
      <td>7.1</td>
      <td>7.6</td>
      <td>7.4</td>
      <td>6.7</td>
      <td>6.0</td>
      <td>5.5</td>
      <td>5.6</td>
      <td>6.0</td>
    </tr>
    <tr>
      <th>1959</th>
      <td>7.0</td>
      <td>7.0</td>
      <td>6.4</td>
      <td>5.2</td>
      <td>4.9</td>
      <td>5.4</td>
      <td>5.2</td>
      <td>4.8</td>
      <td>4.7</td>
      <td>4.7</td>
      <td>5.3</td>
      <td>5.1</td>
    </tr>
    <tr>
      <th>1960</th>
      <td>6.1</td>
      <td>5.7</td>
      <td>6.1</td>
      <td>5.2</td>
      <td>4.8</td>
      <td>5.8</td>
      <td>5.5</td>
      <td>5.2</td>
      <td>4.7</td>
      <td>5.0</td>
      <td>5.6</td>
      <td>6.4</td>
    </tr>
    <tr>
      <th>1961</th>
      <td>7.7</td>
      <td>8.1</td>
      <td>7.7</td>
      <td>7.0</td>
      <td>6.6</td>
      <td>7.3</td>
      <td>6.9</td>
      <td>6.2</td>
      <td>5.8</td>
      <td>5.5</td>
      <td>5.6</td>
      <td>5.8</td>
    </tr>
    <tr>
      <th>1962</th>
      <td>6.7</td>
      <td>6.5</td>
      <td>6.2</td>
      <td>5.5</td>
      <td>5.1</td>
      <td>5.9</td>
      <td>5.3</td>
      <td>5.3</td>
      <td>4.9</td>
      <td>4.5</td>
      <td>5.3</td>
      <td>5.3</td>
    </tr>
    <tr>
      <th>1963</th>
      <td>6.6</td>
      <td>6.9</td>
      <td>6.3</td>
      <td>5.6</td>
      <td>5.5</td>
      <td>6.2</td>
      <td>5.6</td>
      <td>5.2</td>
      <td>4.8</td>
      <td>4.7</td>
      <td>5.3</td>
      <td>5.3</td>
    </tr>
    <tr>
      <th>1964</th>
      <td>6.4</td>
      <td>6.2</td>
      <td>5.9</td>
      <td>5.3</td>
      <td>4.8</td>
      <td>5.9</td>
      <td>4.9</td>
      <td>4.8</td>
      <td>4.5</td>
      <td>4.4</td>
      <td>4.5</td>
      <td>4.7</td>
    </tr>
    <tr>
      <th>1965</th>
      <td>5.5</td>
      <td>5.7</td>
      <td>5.1</td>
      <td>4.7</td>
      <td>4.3</td>
      <td>5.3</td>
      <td>4.5</td>
      <td>4.2</td>
      <td>3.8</td>
      <td>3.6</td>
      <td>3.9</td>
      <td>3.7</td>
    </tr>
    <tr>
      <th>1966</th>
      <td>4.4</td>
      <td>4.2</td>
      <td>4.0</td>
      <td>3.6</td>
      <td>3.7</td>
      <td>4.6</td>
      <td>3.9</td>
      <td>3.6</td>
      <td>3.3</td>
      <td>3.2</td>
      <td>3.4</td>
      <td>3.5</td>
    </tr>
    <tr>
      <th>1967</th>
      <td>4.2</td>
      <td>4.2</td>
      <td>3.9</td>
      <td>3.5</td>
      <td>3.2</td>
      <td>4.6</td>
      <td>4.1</td>
      <td>3.7</td>
      <td>3.7</td>
      <td>3.8</td>
      <td>3.7</td>
      <td>3.5</td>
    </tr>
    <tr>
      <th>1968</th>
      <td>4.0</td>
      <td>4.2</td>
      <td>3.8</td>
      <td>3.2</td>
      <td>2.9</td>
      <td>4.5</td>
      <td>4.0</td>
      <td>3.5</td>
      <td>3.3</td>
      <td>3.2</td>
      <td>3.3</td>
      <td>3.1</td>
    </tr>
    <tr>
      <th>1969</th>
      <td>3.7</td>
      <td>3.7</td>
      <td>3.5</td>
      <td>3.2</td>
      <td>2.9</td>
      <td>4.1</td>
      <td>3.8</td>
      <td>3.5</td>
      <td>3.7</td>
      <td>3.5</td>
      <td>3.3</td>
      <td>3.2</td>
    </tr>
    <tr>
      <th>1970</th>
      <td>4.2</td>
      <td>4.7</td>
      <td>4.6</td>
      <td>4.3</td>
      <td>4.1</td>
      <td>5.6</td>
      <td>5.3</td>
      <td>5.0</td>
      <td>5.2</td>
      <td>5.1</td>
      <td>5.5</td>
      <td>5.6</td>
    </tr>
    <tr>
      <th>1971</th>
      <td>6.6</td>
      <td>6.6</td>
      <td>6.3</td>
      <td>5.7</td>
      <td>5.3</td>
      <td>6.5</td>
      <td>6.2</td>
      <td>5.9</td>
      <td>5.8</td>
      <td>5.4</td>
      <td>5.7</td>
      <td>5.5</td>
    </tr>
    <tr>
      <th>1972</th>
      <td>6.5</td>
      <td>6.4</td>
      <td>6.1</td>
      <td>5.5</td>
      <td>5.1</td>
      <td>6.2</td>
      <td>5.9</td>
      <td>5.5</td>
      <td>5.4</td>
      <td>5.1</td>
      <td>4.9</td>
      <td>4.8</td>
    </tr>
    <tr>
      <th>1973</th>
      <td>5.5</td>
      <td>5.6</td>
      <td>5.2</td>
      <td>4.8</td>
      <td>4.4</td>
      <td>5.4</td>
      <td>5.0</td>
      <td>4.7</td>
      <td>4.7</td>
      <td>4.2</td>
      <td>4.6</td>
      <td>4.6</td>
    </tr>
    <tr>
      <th>1974</th>
      <td>5.7</td>
      <td>5.8</td>
      <td>5.3</td>
      <td>4.8</td>
      <td>4.6</td>
      <td>5.8</td>
      <td>5.7</td>
      <td>5.3</td>
      <td>5.7</td>
      <td>5.5</td>
      <td>6.2</td>
      <td>6.7</td>
    </tr>
    <tr>
      <th>1975</th>
      <td>9.0</td>
      <td>9.1</td>
      <td>9.1</td>
      <td>8.6</td>
      <td>8.3</td>
      <td>9.1</td>
      <td>8.7</td>
      <td>8.2</td>
      <td>8.1</td>
      <td>7.8</td>
      <td>7.8</td>
      <td>7.8</td>
    </tr>
    <tr>
      <th>1976</th>
      <td>8.8</td>
      <td>8.7</td>
      <td>8.1</td>
      <td>7.4</td>
      <td>6.8</td>
      <td>8.0</td>
      <td>7.8</td>
      <td>7.6</td>
      <td>7.4</td>
      <td>7.2</td>
      <td>7.4</td>
      <td>7.4</td>
    </tr>
    <tr>
      <th>1977</th>
      <td>8.3</td>
      <td>8.5</td>
      <td>7.9</td>
      <td>6.9</td>
      <td>6.4</td>
      <td>7.5</td>
      <td>7.0</td>
      <td>6.8</td>
      <td>6.6</td>
      <td>6.4</td>
      <td>6.5</td>
      <td>6.0</td>
    </tr>
    <tr>
      <th>...</th>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
    </tr>
    <tr>
      <th>1987</th>
      <td>7.3</td>
      <td>7.2</td>
      <td>6.9</td>
      <td>6.2</td>
      <td>6.1</td>
      <td>6.3</td>
      <td>6.1</td>
      <td>5.8</td>
      <td>5.7</td>
      <td>5.7</td>
      <td>5.6</td>
      <td>5.4</td>
    </tr>
    <tr>
      <th>1988</th>
      <td>6.3</td>
      <td>6.2</td>
      <td>5.9</td>
      <td>5.3</td>
      <td>5.4</td>
      <td>5.5</td>
      <td>5.5</td>
      <td>5.4</td>
      <td>5.2</td>
      <td>5.0</td>
      <td>5.2</td>
      <td>5.0</td>
    </tr>
    <tr>
      <th>1989</th>
      <td>6.0</td>
      <td>5.6</td>
      <td>5.2</td>
      <td>5.1</td>
      <td>5.0</td>
      <td>5.5</td>
      <td>5.3</td>
      <td>5.1</td>
      <td>5.1</td>
      <td>5.0</td>
      <td>5.2</td>
      <td>5.1</td>
    </tr>
    <tr>
      <th>1990</th>
      <td>6.0</td>
      <td>5.9</td>
      <td>5.5</td>
      <td>5.3</td>
      <td>5.2</td>
      <td>5.4</td>
      <td>5.6</td>
      <td>5.5</td>
      <td>5.6</td>
      <td>5.5</td>
      <td>5.9</td>
      <td>6.0</td>
    </tr>
    <tr>
      <th>1991</th>
      <td>7.1</td>
      <td>7.3</td>
      <td>7.2</td>
      <td>6.5</td>
      <td>6.7</td>
      <td>7.0</td>
      <td>6.8</td>
      <td>6.6</td>
      <td>6.5</td>
      <td>6.5</td>
      <td>6.7</td>
      <td>6.9</td>
    </tr>
    <tr>
      <th>1992</th>
      <td>8.1</td>
      <td>8.2</td>
      <td>7.8</td>
      <td>7.2</td>
      <td>7.3</td>
      <td>8.0</td>
      <td>7.7</td>
      <td>7.4</td>
      <td>7.3</td>
      <td>6.9</td>
      <td>7.1</td>
      <td>7.1</td>
    </tr>
    <tr>
      <th>1993</th>
      <td>8.0</td>
      <td>7.8</td>
      <td>7.4</td>
      <td>6.9</td>
      <td>6.8</td>
      <td>7.2</td>
      <td>7.0</td>
      <td>6.6</td>
      <td>6.4</td>
      <td>6.4</td>
      <td>6.2</td>
      <td>6.1</td>
    </tr>
    <tr>
      <th>1994</th>
      <td>7.3</td>
      <td>7.1</td>
      <td>6.8</td>
      <td>6.2</td>
      <td>5.9</td>
      <td>6.2</td>
      <td>6.2</td>
      <td>5.9</td>
      <td>5.6</td>
      <td>5.4</td>
      <td>5.3</td>
      <td>5.1</td>
    </tr>
    <tr>
      <th>1995</th>
      <td>6.2</td>
      <td>5.9</td>
      <td>5.7</td>
      <td>5.6</td>
      <td>5.5</td>
      <td>5.8</td>
      <td>5.9</td>
      <td>5.6</td>
      <td>5.4</td>
      <td>5.2</td>
      <td>5.3</td>
      <td>5.2</td>
    </tr>
    <tr>
      <th>1996</th>
      <td>6.3</td>
      <td>6.0</td>
      <td>5.8</td>
      <td>5.4</td>
      <td>5.4</td>
      <td>5.5</td>
      <td>5.6</td>
      <td>5.1</td>
      <td>5.0</td>
      <td>4.9</td>
      <td>5.0</td>
      <td>5.0</td>
    </tr>
    <tr>
      <th>1997</th>
      <td>5.9</td>
      <td>5.7</td>
      <td>5.5</td>
      <td>4.8</td>
      <td>4.7</td>
      <td>5.2</td>
      <td>5.0</td>
      <td>4.8</td>
      <td>4.7</td>
      <td>4.4</td>
      <td>4.3</td>
      <td>4.4</td>
    </tr>
    <tr>
      <th>1998</th>
      <td>5.2</td>
      <td>5.0</td>
      <td>5.0</td>
      <td>4.1</td>
      <td>4.2</td>
      <td>4.7</td>
      <td>4.7</td>
      <td>4.5</td>
      <td>4.4</td>
      <td>4.2</td>
      <td>4.1</td>
      <td>4.0</td>
    </tr>
    <tr>
      <th>1999</th>
      <td>4.8</td>
      <td>4.7</td>
      <td>4.4</td>
      <td>4.1</td>
      <td>4.0</td>
      <td>4.5</td>
      <td>4.5</td>
      <td>4.2</td>
      <td>4.1</td>
      <td>3.8</td>
      <td>3.8</td>
      <td>3.7</td>
    </tr>
    <tr>
      <th>2000</th>
      <td>4.5</td>
      <td>4.4</td>
      <td>4.3</td>
      <td>3.7</td>
      <td>3.8</td>
      <td>4.1</td>
      <td>4.2</td>
      <td>4.1</td>
      <td>3.8</td>
      <td>3.6</td>
      <td>3.7</td>
      <td>3.7</td>
    </tr>
    <tr>
      <th>2001</th>
      <td>4.7</td>
      <td>4.6</td>
      <td>4.5</td>
      <td>4.2</td>
      <td>4.1</td>
      <td>4.7</td>
      <td>4.7</td>
      <td>4.9</td>
      <td>4.7</td>
      <td>5.0</td>
      <td>5.3</td>
      <td>5.4</td>
    </tr>
    <tr>
      <th>2002</th>
      <td>6.3</td>
      <td>6.1</td>
      <td>6.1</td>
      <td>5.7</td>
      <td>5.5</td>
      <td>6.0</td>
      <td>5.9</td>
      <td>5.7</td>
      <td>5.4</td>
      <td>5.3</td>
      <td>5.6</td>
      <td>5.7</td>
    </tr>
    <tr>
      <th>2003</th>
      <td>6.5</td>
      <td>6.4</td>
      <td>6.2</td>
      <td>5.8</td>
      <td>5.8</td>
      <td>6.5</td>
      <td>6.3</td>
      <td>6.0</td>
      <td>5.8</td>
      <td>5.6</td>
      <td>5.6</td>
      <td>5.4</td>
    </tr>
    <tr>
      <th>2004</th>
      <td>6.3</td>
      <td>6.0</td>
      <td>6.0</td>
      <td>5.4</td>
      <td>5.3</td>
      <td>5.8</td>
      <td>5.7</td>
      <td>5.4</td>
      <td>5.1</td>
      <td>5.1</td>
      <td>5.2</td>
      <td>5.1</td>
    </tr>
    <tr>
      <th>2005</th>
      <td>5.7</td>
      <td>5.8</td>
      <td>5.4</td>
      <td>4.9</td>
      <td>4.9</td>
      <td>5.2</td>
      <td>5.2</td>
      <td>4.9</td>
      <td>4.8</td>
      <td>4.6</td>
      <td>4.8</td>
      <td>4.6</td>
    </tr>
    <tr>
      <th>2006</th>
      <td>5.1</td>
      <td>5.1</td>
      <td>4.8</td>
      <td>4.5</td>
      <td>4.4</td>
      <td>4.8</td>
      <td>5.0</td>
      <td>4.6</td>
      <td>4.4</td>
      <td>4.1</td>
      <td>4.3</td>
      <td>4.3</td>
    </tr>
    <tr>
      <th>2007</th>
      <td>5.0</td>
      <td>4.9</td>
      <td>4.5</td>
      <td>4.3</td>
      <td>4.3</td>
      <td>4.7</td>
      <td>4.9</td>
      <td>4.6</td>
      <td>4.5</td>
      <td>4.4</td>
      <td>4.5</td>
      <td>4.8</td>
    </tr>
    <tr>
      <th>2008</th>
      <td>5.4</td>
      <td>5.2</td>
      <td>5.2</td>
      <td>4.8</td>
      <td>5.2</td>
      <td>5.7</td>
      <td>6.0</td>
      <td>6.1</td>
      <td>6.0</td>
      <td>6.1</td>
      <td>6.5</td>
      <td>7.1</td>
    </tr>
    <tr>
      <th>2009</th>
      <td>8.5</td>
      <td>8.9</td>
      <td>9.0</td>
      <td>8.6</td>
      <td>9.1</td>
      <td>9.7</td>
      <td>9.7</td>
      <td>9.6</td>
      <td>9.5</td>
      <td>9.5</td>
      <td>9.4</td>
      <td>9.7</td>
    </tr>
    <tr>
      <th>2010</th>
      <td>10.6</td>
      <td>10.4</td>
      <td>10.2</td>
      <td>9.5</td>
      <td>9.3</td>
      <td>9.6</td>
      <td>9.7</td>
      <td>9.5</td>
      <td>9.2</td>
      <td>9.0</td>
      <td>9.3</td>
      <td>9.1</td>
    </tr>
    <tr>
      <th>2011</th>
      <td>9.8</td>
      <td>9.5</td>
      <td>9.2</td>
      <td>8.7</td>
      <td>8.7</td>
      <td>9.3</td>
      <td>9.3</td>
      <td>9.1</td>
      <td>8.8</td>
      <td>8.5</td>
      <td>8.2</td>
      <td>8.3</td>
    </tr>
    <tr>
      <th>2012</th>
      <td>8.8</td>
      <td>8.7</td>
      <td>8.4</td>
      <td>7.7</td>
      <td>7.9</td>
      <td>8.4</td>
      <td>8.6</td>
      <td>8.2</td>
      <td>7.6</td>
      <td>7.5</td>
      <td>7.4</td>
      <td>7.6</td>
    </tr>
    <tr>
      <th>2013</th>
      <td>8.5</td>
      <td>8.1</td>
      <td>7.6</td>
      <td>7.1</td>
      <td>7.3</td>
      <td>7.8</td>
      <td>7.7</td>
      <td>7.3</td>
      <td>7.0</td>
      <td>7.0</td>
      <td>6.6</td>
      <td>6.5</td>
    </tr>
    <tr>
      <th>2014</th>
      <td>7.0</td>
      <td>7.0</td>
      <td>6.8</td>
      <td>5.9</td>
      <td>6.1</td>
      <td>6.3</td>
      <td>6.5</td>
      <td>6.3</td>
      <td>5.7</td>
      <td>5.5</td>
      <td>5.5</td>
      <td>5.4</td>
    </tr>
    <tr>
      <th>2015</th>
      <td>6.1</td>
      <td>5.8</td>
      <td>5.6</td>
      <td>5.1</td>
      <td>5.3</td>
      <td>5.5</td>
      <td>5.6</td>
      <td>5.2</td>
      <td>4.9</td>
      <td>4.8</td>
      <td>4.8</td>
      <td>4.8</td>
    </tr>
    <tr>
      <th>2016</th>
      <td>5.3</td>
      <td>5.2</td>
      <td>5.1</td>
      <td>4.7</td>
      <td>4.5</td>
      <td>5.1</td>
      <td>5.1</td>
      <td>5.0</td>
      <td>4.8</td>
      <td>4.7</td>
      <td>4.4</td>
      <td>4.5</td>
    </tr>
  </tbody>
</table>
<p>69 rows × 12 columns</p>
</div>

In [10]:
years = list(data.index)
months = list(data.columns)
colors = ["#75968f", "#a5bab7", "#c9d9d3", "#e2e2e2", "#dfccce", "#ddb7b1", "#cc7878", "#933b41", "#550b1d"]
TOOLS = "hover,save,pan,box_zoom,reset,wheel_zoom"

In [11]:
df = pd.DataFrame(data.stack(), columns=['rate']).reset_index()
df

<div>
<style>
    .dataframe thead tr:only-child th {
        text-align: right;
    }

    .dataframe thead th {
        text-align: left;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>Year</th>
      <th>Month</th>
      <th>rate</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>1948</td>
      <td>Jan</td>
      <td>4.0</td>
    </tr>
    <tr>
      <th>1</th>
      <td>1948</td>
      <td>Feb</td>
      <td>4.7</td>
    </tr>
    <tr>
      <th>2</th>
      <td>1948</td>
      <td>Mar</td>
      <td>4.5</td>
    </tr>
    <tr>
      <th>3</th>
      <td>1948</td>
      <td>Apr</td>
      <td>4.0</td>
    </tr>
    <tr>
      <th>4</th>
      <td>1948</td>
      <td>May</td>
      <td>3.4</td>
    </tr>
    <tr>
      <th>5</th>
      <td>1948</td>
      <td>Jun</td>
      <td>3.9</td>
    </tr>
    <tr>
      <th>6</th>
      <td>1948</td>
      <td>Jul</td>
      <td>3.9</td>
    </tr>
    <tr>
      <th>7</th>
      <td>1948</td>
      <td>Aug</td>
      <td>3.6</td>
    </tr>
    <tr>
      <th>8</th>
      <td>1948</td>
      <td>Sep</td>
      <td>3.4</td>
    </tr>
    <tr>
      <th>9</th>
      <td>1948</td>
      <td>Oct</td>
      <td>2.9</td>
    </tr>
    <tr>
      <th>10</th>
      <td>1948</td>
      <td>Nov</td>
      <td>3.3</td>
    </tr>
    <tr>
      <th>11</th>
      <td>1948</td>
      <td>Dec</td>
      <td>3.6</td>
    </tr>
    <tr>
      <th>12</th>
      <td>1949</td>
      <td>Jan</td>
      <td>5.0</td>
    </tr>
    <tr>
      <th>13</th>
      <td>1949</td>
      <td>Feb</td>
      <td>5.8</td>
    </tr>
    <tr>
      <th>14</th>
      <td>1949</td>
      <td>Mar</td>
      <td>5.6</td>
    </tr>
    <tr>
      <th>15</th>
      <td>1949</td>
      <td>Apr</td>
      <td>5.4</td>
    </tr>
    <tr>
      <th>16</th>
      <td>1949</td>
      <td>May</td>
      <td>5.7</td>
    </tr>
    <tr>
      <th>17</th>
      <td>1949</td>
      <td>Jun</td>
      <td>6.4</td>
    </tr>
    <tr>
      <th>18</th>
      <td>1949</td>
      <td>Jul</td>
      <td>7.0</td>
    </tr>
    <tr>
      <th>19</th>
      <td>1949</td>
      <td>Aug</td>
      <td>6.3</td>
    </tr>
    <tr>
      <th>20</th>
      <td>1949</td>
      <td>Sep</td>
      <td>5.9</td>
    </tr>
    <tr>
      <th>21</th>
      <td>1949</td>
      <td>Oct</td>
      <td>6.1</td>
    </tr>
    <tr>
      <th>22</th>
      <td>1949</td>
      <td>Nov</td>
      <td>5.7</td>
    </tr>
    <tr>
      <th>23</th>
      <td>1949</td>
      <td>Dec</td>
      <td>6.0</td>
    </tr>
    <tr>
      <th>24</th>
      <td>1950</td>
      <td>Jan</td>
      <td>7.6</td>
    </tr>
    <tr>
      <th>25</th>
      <td>1950</td>
      <td>Feb</td>
      <td>7.9</td>
    </tr>
    <tr>
      <th>26</th>
      <td>1950</td>
      <td>Mar</td>
      <td>7.1</td>
    </tr>
    <tr>
      <th>27</th>
      <td>1950</td>
      <td>Apr</td>
      <td>6.0</td>
    </tr>
    <tr>
      <th>28</th>
      <td>1950</td>
      <td>May</td>
      <td>5.3</td>
    </tr>
    <tr>
      <th>29</th>
      <td>1950</td>
      <td>Jun</td>
      <td>5.6</td>
    </tr>
    <tr>
      <th>...</th>
      <td>...</td>
      <td>...</td>
      <td>...</td>
    </tr>
    <tr>
      <th>798</th>
      <td>2014</td>
      <td>Jul</td>
      <td>6.5</td>
    </tr>
    <tr>
      <th>799</th>
      <td>2014</td>
      <td>Aug</td>
      <td>6.3</td>
    </tr>
    <tr>
      <th>800</th>
      <td>2014</td>
      <td>Sep</td>
      <td>5.7</td>
    </tr>
    <tr>
      <th>801</th>
      <td>2014</td>
      <td>Oct</td>
      <td>5.5</td>
    </tr>
    <tr>
      <th>802</th>
      <td>2014</td>
      <td>Nov</td>
      <td>5.5</td>
    </tr>
    <tr>
      <th>803</th>
      <td>2014</td>
      <td>Dec</td>
      <td>5.4</td>
    </tr>
    <tr>
      <th>804</th>
      <td>2015</td>
      <td>Jan</td>
      <td>6.1</td>
    </tr>
    <tr>
      <th>805</th>
      <td>2015</td>
      <td>Feb</td>
      <td>5.8</td>
    </tr>
    <tr>
      <th>806</th>
      <td>2015</td>
      <td>Mar</td>
      <td>5.6</td>
    </tr>
    <tr>
      <th>807</th>
      <td>2015</td>
      <td>Apr</td>
      <td>5.1</td>
    </tr>
    <tr>
      <th>808</th>
      <td>2015</td>
      <td>May</td>
      <td>5.3</td>
    </tr>
    <tr>
      <th>809</th>
      <td>2015</td>
      <td>Jun</td>
      <td>5.5</td>
    </tr>
    <tr>
      <th>810</th>
      <td>2015</td>
      <td>Jul</td>
      <td>5.6</td>
    </tr>
    <tr>
      <th>811</th>
      <td>2015</td>
      <td>Aug</td>
      <td>5.2</td>
    </tr>
    <tr>
      <th>812</th>
      <td>2015</td>
      <td>Sep</td>
      <td>4.9</td>
    </tr>
    <tr>
      <th>813</th>
      <td>2015</td>
      <td>Oct</td>
      <td>4.8</td>
    </tr>
    <tr>
      <th>814</th>
      <td>2015</td>
      <td>Nov</td>
      <td>4.8</td>
    </tr>
    <tr>
      <th>815</th>
      <td>2015</td>
      <td>Dec</td>
      <td>4.8</td>
    </tr>
    <tr>
      <th>816</th>
      <td>2016</td>
      <td>Jan</td>
      <td>5.3</td>
    </tr>
    <tr>
      <th>817</th>
      <td>2016</td>
      <td>Feb</td>
      <td>5.2</td>
    </tr>
    <tr>
      <th>818</th>
      <td>2016</td>
      <td>Mar</td>
      <td>5.1</td>
    </tr>
    <tr>
      <th>819</th>
      <td>2016</td>
      <td>Apr</td>
      <td>4.7</td>
    </tr>
    <tr>
      <th>820</th>
      <td>2016</td>
      <td>May</td>
      <td>4.5</td>
    </tr>
    <tr>
      <th>821</th>
      <td>2016</td>
      <td>Jun</td>
      <td>5.1</td>
    </tr>
    <tr>
      <th>822</th>
      <td>2016</td>
      <td>Jul</td>
      <td>5.1</td>
    </tr>
    <tr>
      <th>823</th>
      <td>2016</td>
      <td>Aug</td>
      <td>5.0</td>
    </tr>
    <tr>
      <th>824</th>
      <td>2016</td>
      <td>Sep</td>
      <td>4.8</td>
    </tr>
    <tr>
      <th>825</th>
      <td>2016</td>
      <td>Oct</td>
      <td>4.7</td>
    </tr>
    <tr>
      <th>826</th>
      <td>2016</td>
      <td>Nov</td>
      <td>4.4</td>
    </tr>
    <tr>
      <th>827</th>
      <td>2016</td>
      <td>Dec</td>
      <td>4.5</td>
    </tr>
  </tbody>
</table>
<p>828 rows × 3 columns</p>
</div>

In [ ]:
mapper = LinearColorMapper(palette=colors, low=df.rate.min(), high=df.rate.max())
source = ColumnDataSource(df)